name: context
on: push
jobs:
  dump_context_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the action
        uses: actions/checkout@v4
        with: 
          repository: ananddeshpande1985/GitTraining
          path: GitTraining
      - name: print the current dir
        run: pwd
          

      - name: Dump Github Context
        uses: ./GitTraining/.github/actions
