name: context
on: push
jobs:
  dump_context_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github Context
        env: 
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"