name: Build
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with logs
        run: |
          mkdir ${{ runner.temp }}/build_logs
          echo "Logs from building" > ${{ runner.temp }}/build_logs/build.logs
          exit 0
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload logs on fail
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
         name: Build failure logs
         path: ${{ runner.temp }}/build_logs
